TP_URL = http://www.hpl.hp.com/personal/Hans_Boehm/gc/gc_source/gc-7.2alpha2.tar.gz
TP_DIR = gc-7.2alpha2
TP_LIB = libgc.a
TP_EXTRA_CONFIGURE_ARGS = --with-threads=posix

include $(TP_PACKAGE_MAKEFILE)
