TP_URL = http://www.hpl.hp.com/personal/Hans_Boehm/gc/gc_source/gc-7.1alpha3-080224.tar.gz
TP_DIR = gc-7.1alpha3
TP_LIB = libgc.a
TP_EXTRA_CONFIGURE_ARGS = --with-threads=posix --enable-parallel-mark

include $(TP_PACKAGE_MAKEFILE)
