TP_URL = http://optusnet.dl.sourceforge.net/sourceforge/glew/glew-1.4.0-src.tgz
TP_DIR = glew
TP_LIB = libGLEW.a
TP_PATCH = glew.patch.gz
TP_POSTPATCH = chmod +x configure install-sh

include $(TP_PACKAGE_MAKEFILE)
